#!/usr/bin/env sh

set -em

initialized_check_file="/opt/openeew/.initialized"

if [ -f "${initialized_check_file}" ]; then
  echo "✅ Already initialized, skipping initialization"
else
  echo "⏲ Initializing..."

  if [ -n "${username}" ] && [ -n "${password}" ]; then
    echo "🔑 Using authentication"
    touch /opt/openeew/mosquitto_passwords
    mosquitto_passwd -b /opt/openeew/mosquitto_passwords "${username}" "${password}"
    echo "allow_anonymous false" >> /opt/openeew/mosquitto.conf
    echo "password_file /opt/openeew/mosquitto_passwords" >> /opt/openeew/mosquitto.conf
  else
    echo "⚠ Not using authentication"
  fi

  touch "${initialized_check_file}"
  echo "✅ Initialized"
fi

mosquitto -c /opt/openeew/mosquitto.conf -d
timeout 1m sh -c "until nc -z 127.0.0.1 1883; do sleep 1; done"
echo "🚀 Mosquitto is ready"

watch -n 600 /usr/sbin/logrotate /etc/logrotate.d/* &

python3 /opt/openeew/receive_devices.py --username "${username}" --password "${password}" &
python3 /opt/openeew/receive_earthquakes.py --username "${username}" --password "${password}" &
python3 /opt/openeew/detection.py --username "${username}" --password "${password}"
